### ISSUE TITLE
Request to make it compatible touch devices

### ISSUE THREAD

**Issue by numerized** [erikthalen/jigsaw-puzzle#1]
Hi Erik, 

The best jigsaw algorithm so far I can find!
Any chance you can make this compatible with touch devices ? or I am missing something ?

**Comment by numerized** [comment]
I've found a link that helped me making it work with touch devices, super smooth!

https://gist.github.com/Alex1990/d462cb9f90ed2b1a9390#gistcomment-3836712

**Comment by erikthalen** [comment]
Hey man,
glad you like the puzzle :)
Yeah it would be cool to make it compatible with mobile devices. I'll take a look at this when I have time. Otherwise, feel free to make a PR, if you found a good solution!

**Comment by numerized** [comment]
yeah I found one works well, I'll try to do a PR!

**Comment by erikthalen** [comment]
Changed to pointer-events, and added panning on multitouch. It now works on phones (tested on iphone). It's a little hard to navigate/zoom/control, but it technically works.

**Comment by numerized** [comment]
Hello Erik.

I'm not sure if the latest version is in par with your last statement, but I cannot make this lib usable on iPhone or iPad.
The whole view is scrolling and it's impossible to deactivate this.
Can you look at it, it's very much outside of my understanding.

**Comment by numerized** [comment]
@erikthalen hi brother, is there something we can fix here?
