### ISSUE TITLE
Bug on Safari

### ISSUE THREAD

**Issue by numerized** [erikthalen/jigsaw-puzzle#2]
Hey guys, me again...

On Safari v12 and iPad, I found that some puzzle pieces contain the wrong image and they have a transparent side:

<img width="224" alt="Screenshot 2021-12-09 at 20 32 49" src="https://user-images.githubusercontent.com/166829/145463553-0d374714-0594-450a-98fc-57c6492127af.png">

If you open this link https://6l3f8.csb.app and try, 1 time out of 3, if you hit refresh you'll see the issue.

Cheers, I'm considering using this puzzle lib for a very large scale app on appstore and android.
So far you have the best approach

**Comment by numerized** [comment]
on iOS I can reproduce this bug on all major browsers, Safari, chrome, brave:

![IMG_0050](https://user-images.githubusercontent.com/166829/145467177-a6f920f1-6451-4e6b-bc69-a69380166ee4.jpg)

**Comment by erikthalen** [comment]
Hey, 
apparently [this](https://stackoverflow.com/questions/35500999/cropping-with-drawimage-not-working-in-safari) had something to do with it. I added the gist snippet from the thread and it now works fine in safari again :)

fixed in v1.0.5

**Comment by numerized** [comment]
awesome!! Thanks!
